### ISSUE TITLE
[Discussion] Will EdDSA (Ed25519) be supported in the future?

### ISSUE THREAD

**Issue by hiendaovinh** [base-org/keyspace-client#1]
Hi, I'm trying to integrate Ed25519 keypair with keyspace. It's impossible for now but will keyspace support it in the future?

**Comment by niran** [comment]
Hi @hiendaovinh! Keyspace supports arbitrary authentication logic, so it is technically possible to use Ed25519 keys. However, new authentication mechanisms require custom ZK circuits to be written. We're currently rewriting our circuit framework, but the next release should include documentation for wallet vendors who want to write their own circuits for Keyspace.
